### ISSUE TITLE
Merge implementations?

### ISSUE THREAD

**Issue by iFaxity** [ako-deno/ako#5]
Hey ive got implementations of Keygrip, cookies, fresh, content-disposition, bodyparser, etag, conditional-get, and compose. I was thinking of publishing the package when i saw your implementations and also the same package name, link to repo https://github.com/iFaxity/ako.

Would you be interested in merging some PRs if i publish some changes to add these modules and some other improvements?

**Comment by ngot** [comment]
@iFaxity Glad to hear you already have done those modules. I really appreciate your interests in contribute to this project. Looking forward to reviewing PRs.

Regarding the compose module, I decided not to publish it as a seperate module because I don't that is valuable enough to be reused in the Deno community. So, it is inside the ako repo now.(https://github.com/ako-deno/ako/blob/master/src/compose.ts).

According to https://github.com/ako-deno/ako/issues/4, I still need:

-  content-disposition
-  fresh
-  keygrip
-  cookies
-  tsscmp

Do you want to maintain those modules in this origination(I can create repos for you and invite you as a collaborator) or still let them there?

**Comment by iFaxity** [comment]
@ngot Sure thing. Ive got most of those modules done. Would be awesome to be added as a collaborator. I am also working on a router and multipart parser (multer) using the multipart parser from denos standard library.

Yes it would probably be better to not add the compose module.
